version: '3.11'

services:
  web:
    image: dental_lab
    container_name: dental_lab
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app/dental
      - ../static:/app/dental/staticfiles
    ports:
      - "8000:8000"